// SPDX-License-Identifier: BSD-3-Clause
// Still mask for synth.comp: 1 where a pixel is the same in both frames (its neighbours needn't
// be: a glyph's outline borders the moving scene). That is the HUD over a moving scene, a
// figure the camera keeps still, black bars around a video, and flat colour the motion doesn't
// show in. The scene doesn't move through any of it, so a moving vector that takes a sample
// there is wrong (in flat colour, it would also match anything: bars bled into a loading
// video, HUD colour into the scene).
#version 450
layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0) uniform sampler2D prev_img;
layout(binding = 1) uniform sampler2D cur_img;
layout(binding = 2, rgba8) uniform writeonly image2D dst;

float diff(vec4 x, vec4 y)
{
    vec3 d = abs(x.rgb - y.rgb);
    return d.r + d.g + d.b;
}

void main()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(dst);
    if (any(greaterThanEqual(p, size)))
        return;
    float moved = diff(texelFetch(prev_img, p, 0), texelFetch(cur_img, p, 0));
    imageStore(dst, p, vec4(moved < 0.02 ? 1.0 : 0.0));
}
