name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y glslang-tools libvulkan-dev
      - run: make
      - run: make install DESTDIR="$PWD/stage" && find stage -type f
